nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['^https?://((front|admin|api)\.playlisto\.com)(:[0-9]+)?$']
        origin_regex: true
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH', 'PUT']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['^https?://((front|admin|api)\.playlisto\.com)(:[0-9]+)?$']
            allow_credentials: true
            origin_regex: true
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH', 'PUT']
            max_age: 3600