services:
  db:
    image: mariadb
    container_name: playlisto_docker_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - playlisto-db-data:/var/lib/mariadb
    networks:
      - dev
    ports:
      - "33306:33306"

  php:
    container_name: playlisto_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - dev

  nginx:
    container_name: playlisto_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - dev

networks:
  dev:

volumes:
  playlisto-db-data: