services:
  db:
    image: mariadb
    container_name: playlisto_docker_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - playlisto-db-data:/var/lib/mariadb
    networks:
      - dev
    ports:
      - "33306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: playlisto_rabbitmq
    volumes:
      - rmqconf:/etc/rabbitmq
      - rmqdata:/var/lib/rabbitmq/mnesia
      - rmqlogs:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - dev

  php-fpm:
    container_name: playlisto_php-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - rabbitmq
    networks:
      - dev

  nginx:
    image: nginx:latest
    container_name: playlisto_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default.conf
      - ./docker/nginx/conf.d.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - php-fpm
    networks:
      - dev

networks:
  dev:

volumes:
  playlisto-db-data:
  rmqconf:
    driver: local
  rmqdata:
    driver: local
  rmqlogs:
    driver: local