api_platform:
  resource: .
  type: api_platform
  prefix: /api

api_auth_login:
  path: /api/authentication_token
  controller: App\Controller\Api\AuthController
  methods: ['POST']

api_token_refresh:
  path: /api/token/refresh
  controller: App\Controller\Api\TokenRefreshController
  methods: ['POST']

api_signup:
  path: /api/signup
  controller: App\Controller\Api\SignupController
  methods: ['POST']