api:
    resource: '../src/Controller/Api'
    type: attribute
    host: '%api_domain_default%'

back:
    name_prefix: 'back_'
    resource: ../src/Controller/Back
    type: attribute
    host: '%back_domain_default%'

front:
    name_prefix: 'front_'
    resource: ../src/Controller/Front
    type: attribute
    host: '%front_domain_default%'

app:
    resource: ../src/Controller/**/*
    exclude:
        - ../src/Controller/Back
        - ../src/Controller/Front
        - ../src/Controller/Api
    type: attribute