controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

back:
    name_prefix: 'back_'
    resource: ../src/Controller/Back
    type: attribute
    host: '%back_domain_default%'

front:
    name_prefix: 'front_'
    resource: ../src/Controller/Front
    type: attribute
    host: '%front_domain_default%'