# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    back_paginate_max_per_page: '%env(int:BACK_PAGINATE_MAX_PER_PAGE)%'

    # BACK
    back_domain_default: '%env(APP_ADMIN_HOST)%'

    # FRONT
    front_domain_default: '%env(APP_FRONT_HOST)%'

    # API
    api_domain_default: '%env(APP_API_HOST)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Migrations/'

    App\Controller\:
        resource: '../src/Controller/'
        public: true
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    App\Service\OpenAIService:
      arguments:
        $httpClient: '@http_client'
        $apiKey: '%env(OPENAI_API_KEY)%'
        $model: '%env(default::string:OPENAI_MODEL)%'
        $timeout: '%env(int:OPENAI_TIMEOUT)%'

    App\Service\SpotifyService:
      arguments:
        $http: '@http_client'
        $cache: '@cache.app'
        $clientId: '%env(SPOTIFY_CLIENT_ID)%'
        $clientSecret: '%env(SPOTIFY_CLIENT_SECRET)%'
        $baseUrl: '%env(SPOTIFY_API_BASE)%'

    # Firewall for Host
    App\Service\FirewallDetector:
        arguments:
            $firewallMap: '@security.firewall.map'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
