<?php

namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use App\Entity\Recommendation;
use App\Entity\User;

class RecommendationFixtures extends Fixture implements OrderedFixtureInterface
{
    public function load(ObjectManager $manager): void
    {
        $users = $manager->getRepository(User::class)->findAll();
        if (empty($users)) {
            throw new \RuntimeException('No users found. Make sure UserFixtures are loaded first.');
        }
        for ($i = 0; $i < 10; $i++) {
            $recommendation = new Recommendation();
            $recommendation->setSource('Generated by ChatGPT');
            $recommendation->setGeneratedAt(new \DateTime(sprintf('-%d days', random_int(0, 30))));
            $recommendation->setUser($users[array_rand($users)]);
            $manager->persist($recommendation);
        }

        $manager->flush();
    }

    /**
     * @return int
     */
    public function getOrder(): int
    {
        return 5;
    }
}
